/* Generated by JSIL v0.8.2 build 30747. See http://jsil.org/ for more information. */ 
'use strict';
var $asm_CSharpXamlForHtml5_System_Runtime_Serialization_dll = JSIL.DeclareAssembly("CSharpXamlForHtml5.System.Runtime.Serialization.dll, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null");

JSIL.DeclareNamespace("System");
JSIL.DeclareNamespace("System.Runtime");
JSIL.DeclareNamespace("System.Runtime.Serialization");
/* class System.Runtime.Serialization.DataMemberAttribute */ 

(function DataMemberAttribute$Members () {
  var $, $thisType;
  var $T00 = function () {
    return ($T00 = JSIL.Memoize($asm_mscorlib.System.Attribute)) ();
  };
  var $T01 = function () {
    return ($T01 = JSIL.Memoize($asm_mscorlib.System.Boolean)) ();
  };
  var $T02 = function () {
    return ($T02 = JSIL.Memoize($asm_mscorlib.System.String)) ();
  };
  var $T03 = function () {
    return ($T03 = JSIL.Memoize($asm_mscorlib.System.Int32)) ();
  };

  function DataMemberAttribute__ctor () {
    $T00().prototype['_ctor'].call(this);
    this.DataMemberAttribute$EmitDefaultValue$value = true;
  };

  function DataMemberAttribute_get_EmitDefaultValue () {
    return this.DataMemberAttribute$EmitDefaultValue$value;
  };

  function DataMemberAttribute_get_IsRequired () {
    return this.DataMemberAttribute$IsRequired$value;
  };

  function DataMemberAttribute_get_Name () {
    return this.DataMemberAttribute$Name$value;
  };

  function DataMemberAttribute_get_Order () {
    return this.DataMemberAttribute$Order$value;
  };

  function DataMemberAttribute_set_EmitDefaultValue (value) {
    this.DataMemberAttribute$EmitDefaultValue$value = value;
  };

  function DataMemberAttribute_set_IsRequired (value) {
    this.DataMemberAttribute$IsRequired$value = value;
  };

  function DataMemberAttribute_set_Name (value) {
    this.DataMemberAttribute$Name$value = value;
  };

  function DataMemberAttribute_set_Order (value) {
    this.DataMemberAttribute$Order$value = (value | 0);
  };

  JSIL.MakeType({
      BaseType: $asm_mscorlib.TypeRef("System.Attribute"), 
      Name: "System.Runtime.Serialization.DataMemberAttribute", 
      IsPublic: true, 
      IsReferenceType: true, 
      MaximumConstructorArguments: 0, 
    }, function ($interfaceBuilder) {
    $ = $interfaceBuilder;

    $.Method({Static:false, Public:true }, ".ctor", 
      JSIL.MethodSignature.Void, 
      DataMemberAttribute__ctor
    );

    $.Method({Static:false, Public:true }, "get_EmitDefaultValue", 
      JSIL.MethodSignature.Return($.Boolean), 
      DataMemberAttribute_get_EmitDefaultValue
    )
      .Attribute($asm_mscorlib.TypeRef("System.Runtime.CompilerServices.CompilerGeneratedAttribute"));

    $.Method({Static:false, Public:true }, "get_IsRequired", 
      JSIL.MethodSignature.Return($.Boolean), 
      DataMemberAttribute_get_IsRequired
    )
      .Attribute($asm_mscorlib.TypeRef("System.Runtime.CompilerServices.CompilerGeneratedAttribute"));

    $.Method({Static:false, Public:true }, "get_Name", 
      JSIL.MethodSignature.Return($.String), 
      DataMemberAttribute_get_Name
    )
      .Attribute($asm_mscorlib.TypeRef("System.Runtime.CompilerServices.CompilerGeneratedAttribute"));

    $.Method({Static:false, Public:true }, "get_Order", 
      JSIL.MethodSignature.Return($.Int32), 
      DataMemberAttribute_get_Order
    )
      .Attribute($asm_mscorlib.TypeRef("System.Runtime.CompilerServices.CompilerGeneratedAttribute"));

    $.Method({Static:false, Public:true }, "set_EmitDefaultValue", 
      JSIL.MethodSignature.Action($.Boolean), 
      DataMemberAttribute_set_EmitDefaultValue
    )
      .Attribute($asm_mscorlib.TypeRef("System.Runtime.CompilerServices.CompilerGeneratedAttribute"));

    $.Method({Static:false, Public:true }, "set_IsRequired", 
      JSIL.MethodSignature.Action($.Boolean), 
      DataMemberAttribute_set_IsRequired
    )
      .Attribute($asm_mscorlib.TypeRef("System.Runtime.CompilerServices.CompilerGeneratedAttribute"));

    $.Method({Static:false, Public:true }, "set_Name", 
      JSIL.MethodSignature.Action($.String), 
      DataMemberAttribute_set_Name
    )
      .Attribute($asm_mscorlib.TypeRef("System.Runtime.CompilerServices.CompilerGeneratedAttribute"));

    $.Method({Static:false, Public:true }, "set_Order", 
      JSIL.MethodSignature.Action($.Int32), 
      DataMemberAttribute_set_Order
    )
      .Attribute($asm_mscorlib.TypeRef("System.Runtime.CompilerServices.CompilerGeneratedAttribute"));

    $['Field']({Static:false, Public:false}, "DataMemberAttribute$EmitDefaultValue$value", $.Boolean)
      .Attribute($asm_mscorlib.TypeRef("System.Runtime.CompilerServices.CompilerGeneratedAttribute")); 
    $['Field']({Static:false, Public:false}, "DataMemberAttribute$IsRequired$value", $.Boolean)
      .Attribute($asm_mscorlib.TypeRef("System.Runtime.CompilerServices.CompilerGeneratedAttribute")); 
    $['Field']({Static:false, Public:false}, "DataMemberAttribute$Name$value", $.String)
      .Attribute($asm_mscorlib.TypeRef("System.Runtime.CompilerServices.CompilerGeneratedAttribute")); 
    $['Field']({Static:false, Public:false}, "DataMemberAttribute$Order$value", $.Int32)
      .Attribute($asm_mscorlib.TypeRef("System.Runtime.CompilerServices.CompilerGeneratedAttribute")); 
    $.Property({Static:false, Public:true }, "EmitDefaultValue", $.Boolean);

    $.Property({Static:false, Public:true }, "IsRequired", $.Boolean);

    $.Property({Static:false, Public:true }, "Name", $.String);

    $.Property({Static:false, Public:true }, "Order", $.Int32);

    $.ImplementInterfaces(
    );

    return function (newThisType) { $thisType = newThisType; }; 
  })
    .Attribute($asm_mscorlib.TypeRef("System.AttributeUsageAttribute"), function () { return [$asm_mscorlib.System.AttributeTargets.$Flags("Field", "Property")]; });

})();

/* class System.Runtime.Serialization.ExtensionDataObject */ 

(function ExtensionDataObject$Members () {
  var $, $thisType;
  function ExtensionDataObject__ctor () {
  };

  JSIL.MakeType({
      BaseType: $asm_mscorlib.TypeRef("System.Object"), 
      Name: "System.Runtime.Serialization.ExtensionDataObject", 
      IsPublic: true, 
      IsReferenceType: true, 
      MaximumConstructorArguments: 0, 
    }, function ($interfaceBuilder) {
    $ = $interfaceBuilder;

    $.Method({Static:false, Public:true }, ".ctor", 
      JSIL.MethodSignature.Void, 
      ExtensionDataObject__ctor
    );

    return function (newThisType) { $thisType = newThisType; }; 
  });

})();

/* interface System.Runtime.Serialization.IExtensibleDataObject */ 

JSIL.MakeInterface(
  "System.Runtime.Serialization.IExtensibleDataObject", true, [], function ($) {
    $.Method({}, "get_ExtensionData", JSIL.MethodSignature.Return($asm_CSharpXamlForHtml5_System_Runtime_Serialization_dll.TypeRef("System.Runtime.Serialization.ExtensionDataObject")));
    $.Method({}, "set_ExtensionData", JSIL.MethodSignature.Action($asm_CSharpXamlForHtml5_System_Runtime_Serialization_dll.TypeRef("System.Runtime.Serialization.ExtensionDataObject")));
    $.Property({}, "ExtensionData");
  }, []);

/* class System.Runtime.Serialization.KnownTypeAttribute */ 

(function KnownTypeAttribute$Members () {
  var $, $thisType;
  var $T00 = function () {
    return ($T00 = JSIL.Memoize($asm_mscorlib.System.Attribute)) ();
  };
  var $T01 = function () {
    return ($T01 = JSIL.Memoize($asm_mscorlib.System.Type)) ();
  };
  var $T02 = function () {
    return ($T02 = JSIL.Memoize($asm_mscorlib.System.String)) ();
  };

  function KnownTypeAttribute__ctor$00 () {
    $T00().prototype['_ctor'].call(this);
  };

  function KnownTypeAttribute__ctor$01 (type) {
    $T00().prototype['_ctor'].call(this);
    this.type = type;
  };

  function KnownTypeAttribute__ctor$02 (methodName) {
    $T00().prototype['_ctor'].call(this);
    this.methodName = methodName;
  };

  function KnownTypeAttribute_get_MethodName () {
    return this.methodName;
  };

  function KnownTypeAttribute_get_Type () {
    return this.type;
  };

  JSIL.MakeType({
      BaseType: $asm_mscorlib.TypeRef("System.Attribute"), 
      Name: "System.Runtime.Serialization.KnownTypeAttribute", 
      IsPublic: true, 
      IsReferenceType: true, 
      MaximumConstructorArguments: 1, 
    }, function ($interfaceBuilder) {
    $ = $interfaceBuilder;

    $.Method({Static:false, Public:false}, ".ctor", 
      JSIL.MethodSignature.Void, 
      KnownTypeAttribute__ctor$00
    );

    $.Method({Static:false, Public:true }, ".ctor", 
      JSIL.MethodSignature.Action($asm_mscorlib.TypeRef("System.Type")), 
      KnownTypeAttribute__ctor$01
    );

    $.Method({Static:false, Public:true }, ".ctor", 
      JSIL.MethodSignature.Action($.String), 
      KnownTypeAttribute__ctor$02
    );

    $.Method({Static:false, Public:true }, "get_MethodName", 
      JSIL.MethodSignature.Return($.String), 
      KnownTypeAttribute_get_MethodName
    );

    $.Method({Static:false, Public:true }, "get_Type", 
      JSIL.MethodSignature.Return($asm_mscorlib.TypeRef("System.Type")), 
      KnownTypeAttribute_get_Type
    );

    $['Field']({Static:false, Public:false}, "methodName", $.String); 
    $['Field']({Static:false, Public:false}, "type", $asm_mscorlib.TypeRef("System.Type")); 
    $.Property({Static:false, Public:true }, "MethodName", $.String);

    $.Property({Static:false, Public:true }, "Type", $asm_mscorlib.TypeRef("System.Type"));

    $.ImplementInterfaces(
    );

    return function (newThisType) { $thisType = newThisType; }; 
  })
    .Attribute($asm_mscorlib.TypeRef("System.AttributeUsageAttribute"), function () { return [$asm_mscorlib.System.AttributeTargets.$Flags("Class", "Struct")]; });

})();

/* class System.Runtime.Serialization.CollectionDataContractAttribute */ 

(function CollectionDataContractAttribute$Members () {
  var $, $thisType;
  var $T00 = function () {
    return ($T00 = JSIL.Memoize($asm_mscorlib.System.Attribute)) ();
  };
  var $T01 = function () {
    return ($T01 = JSIL.Memoize($asm_mscorlib.System.Boolean)) ();
  };
  var $T02 = function () {
    return ($T02 = JSIL.Memoize($asm_mscorlib.System.String)) ();
  };

  function CollectionDataContractAttribute__ctor () {
    $T00().prototype['_ctor'].call(this);
  };

  function CollectionDataContractAttribute_get_IsReference () {
    return this.CollectionDataContractAttribute$IsReference$value;
  };

  function CollectionDataContractAttribute_get_ItemName () {
    return this.CollectionDataContractAttribute$ItemName$value;
  };

  function CollectionDataContractAttribute_get_KeyName () {
    return this.CollectionDataContractAttribute$KeyName$value;
  };

  function CollectionDataContractAttribute_get_Name () {
    return this.CollectionDataContractAttribute$Name$value;
  };

  function CollectionDataContractAttribute_get_Namespace () {
    return this.CollectionDataContractAttribute$Namespace$value;
  };

  function CollectionDataContractAttribute_get_ValueName () {
    return this.CollectionDataContractAttribute$ValueName$value;
  };

  function CollectionDataContractAttribute_set_IsReference (value) {
    this.CollectionDataContractAttribute$IsReference$value = value;
  };

  function CollectionDataContractAttribute_set_ItemName (value) {
    this.CollectionDataContractAttribute$ItemName$value = value;
  };

  function CollectionDataContractAttribute_set_KeyName (value) {
    this.CollectionDataContractAttribute$KeyName$value = value;
  };

  function CollectionDataContractAttribute_set_Name (value) {
    this.CollectionDataContractAttribute$Name$value = value;
  };

  function CollectionDataContractAttribute_set_Namespace (value) {
    this.CollectionDataContractAttribute$Namespace$value = value;
  };

  function CollectionDataContractAttribute_set_ValueName (value) {
    this.CollectionDataContractAttribute$ValueName$value = value;
  };

  JSIL.MakeType({
      BaseType: $asm_mscorlib.TypeRef("System.Attribute"), 
      Name: "System.Runtime.Serialization.CollectionDataContractAttribute", 
      IsPublic: true, 
      IsReferenceType: true, 
      MaximumConstructorArguments: 0, 
    }, function ($interfaceBuilder) {
    $ = $interfaceBuilder;

    $.Method({Static:false, Public:true }, ".ctor", 
      JSIL.MethodSignature.Void, 
      CollectionDataContractAttribute__ctor
    );

    $.Method({Static:false, Public:true }, "get_IsReference", 
      JSIL.MethodSignature.Return($.Boolean), 
      CollectionDataContractAttribute_get_IsReference
    )
      .Attribute($asm_mscorlib.TypeRef("System.Runtime.CompilerServices.CompilerGeneratedAttribute"));

    $.Method({Static:false, Public:true }, "get_ItemName", 
      JSIL.MethodSignature.Return($.String), 
      CollectionDataContractAttribute_get_ItemName
    )
      .Attribute($asm_mscorlib.TypeRef("System.Runtime.CompilerServices.CompilerGeneratedAttribute"));

    $.Method({Static:false, Public:true }, "get_KeyName", 
      JSIL.MethodSignature.Return($.String), 
      CollectionDataContractAttribute_get_KeyName
    )
      .Attribute($asm_mscorlib.TypeRef("System.Runtime.CompilerServices.CompilerGeneratedAttribute"));

    $.Method({Static:false, Public:true }, "get_Name", 
      JSIL.MethodSignature.Return($.String), 
      CollectionDataContractAttribute_get_Name
    )
      .Attribute($asm_mscorlib.TypeRef("System.Runtime.CompilerServices.CompilerGeneratedAttribute"));

    $.Method({Static:false, Public:true }, "get_Namespace", 
      JSIL.MethodSignature.Return($.String), 
      CollectionDataContractAttribute_get_Namespace
    )
      .Attribute($asm_mscorlib.TypeRef("System.Runtime.CompilerServices.CompilerGeneratedAttribute"));

    $.Method({Static:false, Public:true }, "get_ValueName", 
      JSIL.MethodSignature.Return($.String), 
      CollectionDataContractAttribute_get_ValueName
    )
      .Attribute($asm_mscorlib.TypeRef("System.Runtime.CompilerServices.CompilerGeneratedAttribute"));

    $.Method({Static:false, Public:true }, "set_IsReference", 
      JSIL.MethodSignature.Action($.Boolean), 
      CollectionDataContractAttribute_set_IsReference
    )
      .Attribute($asm_mscorlib.TypeRef("System.Runtime.CompilerServices.CompilerGeneratedAttribute"));

    $.Method({Static:false, Public:true }, "set_ItemName", 
      JSIL.MethodSignature.Action($.String), 
      CollectionDataContractAttribute_set_ItemName
    )
      .Attribute($asm_mscorlib.TypeRef("System.Runtime.CompilerServices.CompilerGeneratedAttribute"));

    $.Method({Static:false, Public:true }, "set_KeyName", 
      JSIL.MethodSignature.Action($.String), 
      CollectionDataContractAttribute_set_KeyName
    )
      .Attribute($asm_mscorlib.TypeRef("System.Runtime.CompilerServices.CompilerGeneratedAttribute"));

    $.Method({Static:false, Public:true }, "set_Name", 
      JSIL.MethodSignature.Action($.String), 
      CollectionDataContractAttribute_set_Name
    )
      .Attribute($asm_mscorlib.TypeRef("System.Runtime.CompilerServices.CompilerGeneratedAttribute"));

    $.Method({Static:false, Public:true }, "set_Namespace", 
      JSIL.MethodSignature.Action($.String), 
      CollectionDataContractAttribute_set_Namespace
    )
      .Attribute($asm_mscorlib.TypeRef("System.Runtime.CompilerServices.CompilerGeneratedAttribute"));

    $.Method({Static:false, Public:true }, "set_ValueName", 
      JSIL.MethodSignature.Action($.String), 
      CollectionDataContractAttribute_set_ValueName
    )
      .Attribute($asm_mscorlib.TypeRef("System.Runtime.CompilerServices.CompilerGeneratedAttribute"));

    $['Field']({Static:false, Public:false}, "CollectionDataContractAttribute$IsReference$value", $.Boolean)
      .Attribute($asm_mscorlib.TypeRef("System.Runtime.CompilerServices.CompilerGeneratedAttribute")); 
    $['Field']({Static:false, Public:false}, "CollectionDataContractAttribute$ItemName$value", $.String)
      .Attribute($asm_mscorlib.TypeRef("System.Runtime.CompilerServices.CompilerGeneratedAttribute")); 
    $['Field']({Static:false, Public:false}, "CollectionDataContractAttribute$KeyName$value", $.String)
      .Attribute($asm_mscorlib.TypeRef("System.Runtime.CompilerServices.CompilerGeneratedAttribute")); 
    $['Field']({Static:false, Public:false}, "CollectionDataContractAttribute$Name$value", $.String)
      .Attribute($asm_mscorlib.TypeRef("System.Runtime.CompilerServices.CompilerGeneratedAttribute")); 
    $['Field']({Static:false, Public:false}, "CollectionDataContractAttribute$Namespace$value", $.String)
      .Attribute($asm_mscorlib.TypeRef("System.Runtime.CompilerServices.CompilerGeneratedAttribute")); 
    $['Field']({Static:false, Public:false}, "CollectionDataContractAttribute$ValueName$value", $.String)
      .Attribute($asm_mscorlib.TypeRef("System.Runtime.CompilerServices.CompilerGeneratedAttribute")); 
    $.Property({Static:false, Public:true }, "IsReference", $.Boolean);

    $.Property({Static:false, Public:true }, "ItemName", $.String);

    $.Property({Static:false, Public:true }, "KeyName", $.String);

    $.Property({Static:false, Public:true }, "Name", $.String);

    $.Property({Static:false, Public:true }, "Namespace", $.String);

    $.Property({Static:false, Public:true }, "ValueName", $.String);

    $.ImplementInterfaces(
    );

    return function (newThisType) { $thisType = newThisType; }; 
  })
    .Attribute($asm_mscorlib.TypeRef("System.AttributeUsageAttribute"), function () { return [$asm_mscorlib.System.AttributeTargets.$Flags("Class", "Struct")]; });

})();

/* class System.Runtime.Serialization.DataContractAttribute */ 

(function DataContractAttribute$Members () {
  var $, $thisType;
  var $T00 = function () {
    return ($T00 = JSIL.Memoize($asm_mscorlib.System.Attribute)) ();
  };
  var $T01 = function () {
    return ($T01 = JSIL.Memoize($asm_mscorlib.System.Boolean)) ();
  };
  var $T02 = function () {
    return ($T02 = JSIL.Memoize($asm_mscorlib.System.String)) ();
  };

  function DataContractAttribute__ctor () {
    $T00().prototype['_ctor'].call(this);
  };

  function DataContractAttribute_get_IsReference () {
    return this.DataContractAttribute$IsReference$value;
  };

  function DataContractAttribute_get_Name () {
    return this.DataContractAttribute$Name$value;
  };

  function DataContractAttribute_get_Namespace () {
    return this.DataContractAttribute$Namespace$value;
  };

  function DataContractAttribute_set_IsReference (value) {
    this.DataContractAttribute$IsReference$value = value;
  };

  function DataContractAttribute_set_Name (value) {
    this.DataContractAttribute$Name$value = value;
  };

  function DataContractAttribute_set_Namespace (value) {
    this.DataContractAttribute$Namespace$value = value;
  };

  JSIL.MakeType({
      BaseType: $asm_mscorlib.TypeRef("System.Attribute"), 
      Name: "System.Runtime.Serialization.DataContractAttribute", 
      IsPublic: true, 
      IsReferenceType: true, 
      MaximumConstructorArguments: 0, 
    }, function ($interfaceBuilder) {
    $ = $interfaceBuilder;

    $.Method({Static:false, Public:true }, ".ctor", 
      JSIL.MethodSignature.Void, 
      DataContractAttribute__ctor
    );

    $.Method({Static:false, Public:true }, "get_IsReference", 
      JSIL.MethodSignature.Return($.Boolean), 
      DataContractAttribute_get_IsReference
    )
      .Attribute($asm_mscorlib.TypeRef("System.Runtime.CompilerServices.CompilerGeneratedAttribute"));

    $.Method({Static:false, Public:true }, "get_Name", 
      JSIL.MethodSignature.Return($.String), 
      DataContractAttribute_get_Name
    )
      .Attribute($asm_mscorlib.TypeRef("System.Runtime.CompilerServices.CompilerGeneratedAttribute"));

    $.Method({Static:false, Public:true }, "get_Namespace", 
      JSIL.MethodSignature.Return($.String), 
      DataContractAttribute_get_Namespace
    )
      .Attribute($asm_mscorlib.TypeRef("System.Runtime.CompilerServices.CompilerGeneratedAttribute"));

    $.Method({Static:false, Public:true }, "set_IsReference", 
      JSIL.MethodSignature.Action($.Boolean), 
      DataContractAttribute_set_IsReference
    )
      .Attribute($asm_mscorlib.TypeRef("System.Runtime.CompilerServices.CompilerGeneratedAttribute"));

    $.Method({Static:false, Public:true }, "set_Name", 
      JSIL.MethodSignature.Action($.String), 
      DataContractAttribute_set_Name
    )
      .Attribute($asm_mscorlib.TypeRef("System.Runtime.CompilerServices.CompilerGeneratedAttribute"));

    $.Method({Static:false, Public:true }, "set_Namespace", 
      JSIL.MethodSignature.Action($.String), 
      DataContractAttribute_set_Namespace
    )
      .Attribute($asm_mscorlib.TypeRef("System.Runtime.CompilerServices.CompilerGeneratedAttribute"));

    $['Field']({Static:false, Public:false}, "DataContractAttribute$IsReference$value", $.Boolean)
      .Attribute($asm_mscorlib.TypeRef("System.Runtime.CompilerServices.CompilerGeneratedAttribute")); 
    $['Field']({Static:false, Public:false}, "DataContractAttribute$Name$value", $.String)
      .Attribute($asm_mscorlib.TypeRef("System.Runtime.CompilerServices.CompilerGeneratedAttribute")); 
    $['Field']({Static:false, Public:false}, "DataContractAttribute$Namespace$value", $.String)
      .Attribute($asm_mscorlib.TypeRef("System.Runtime.CompilerServices.CompilerGeneratedAttribute")); 
    $.Property({Static:false, Public:true }, "IsReference", $.Boolean);

    $.Property({Static:false, Public:true }, "Name", $.String);

    $.Property({Static:false, Public:true }, "Namespace", $.String);

    $.ImplementInterfaces(
    );

    return function (newThisType) { $thisType = newThisType; }; 
  })
    .Attribute($asm_mscorlib.TypeRef("System.AttributeUsageAttribute"), function () { return [$asm_mscorlib.System.AttributeTargets.$Flags("Class", "Enum", "Struct")]; });

})();

/* class System.Runtime.Serialization.EnumMemberAttribute */ 

(function EnumMemberAttribute$Members () {
  var $, $thisType;
  var $T00 = function () {
    return ($T00 = JSIL.Memoize($asm_mscorlib.System.Attribute)) ();
  };
  var $T01 = function () {
    return ($T01 = JSIL.Memoize($asm_mscorlib.System.String)) ();
  };

  function EnumMemberAttribute__ctor () {
    $T00().prototype['_ctor'].call(this);
  };

  function EnumMemberAttribute_get_Value () {
    return this.value;
  };

  function EnumMemberAttribute_set_Value (value) {
    this.value = value;
  };

  JSIL.MakeType({
      BaseType: $asm_mscorlib.TypeRef("System.Attribute"), 
      Name: "System.Runtime.Serialization.EnumMemberAttribute", 
      IsPublic: true, 
      IsReferenceType: true, 
      MaximumConstructorArguments: 0, 
    }, function ($interfaceBuilder) {
    $ = $interfaceBuilder;

    $.Method({Static:false, Public:true }, ".ctor", 
      JSIL.MethodSignature.Void, 
      EnumMemberAttribute__ctor
    );

    $.Method({Static:false, Public:true }, "get_Value", 
      JSIL.MethodSignature.Return($.String), 
      EnumMemberAttribute_get_Value
    );

    $.Method({Static:false, Public:true }, "set_Value", 
      JSIL.MethodSignature.Action($.String), 
      EnumMemberAttribute_set_Value
    );

    $['Field']({Static:false, Public:false}, "value", $.String); 
    $.Property({Static:false, Public:true }, "Value", $.String);

    $.ImplementInterfaces(
    );

    return function (newThisType) { $thisType = newThisType; }; 
  })
    .Attribute($asm_mscorlib.TypeRef("System.AttributeUsageAttribute"), function () { return [$asm_mscorlib.System.AttributeTargets.Field]; });

})();

